### ISSUE TITLE
Latest wifi.py with ESP32

### ISSUE THREAD

**Issue by davefes** [glenn20/micropython-espnow-utils#1]
```
>>> 
MPY: soft reboot
Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "wifi.py", line 122, in reset
  File "wifi.py", line 97, in disconnect
  File "wifi.py", line 91, in wait_for
TimeoutError: 

```
I see quite a few code changes, does something needs to change in how it is used?

**Comment by davefes** [comment]
Appears to be working today!
